### ISSUE TITLE
Basic QA/QC tool?

### ISSUE THREAD

**Issue by jb388** [SoilBGC-Datashare/sidb#1]
@aahoyt @CaitlinPries @christinaschaedel @crlsierra @mazizirad @ShaneStoner @susanecrow 

I've been working on an R report tool to simplify and improve querying in sidb, and I've run into several QA/QC issues that have required manual edits of templates. I think it could be helpful for the future (assuming we enter more studies) to build at least some sort of simple QA/QC tool. Additionally, formalizing the template entry procedure in some sort of document would also be incredibly helpful, both to serve as a QA/QC reference, and for working on future entries.

Specific issues:
- ensure that the length and names match exactly (case and all) between the names fields in the 'variables' section of the metadata.yaml file and the names of the columns in the timeSeries.csv file
- adherence to our agreed upon units and exact matches

Others? Volunteers to work on either of these projects...? : )

**Comment by CaitlinPries** [comment]
Jeff et al.,

Thanks for looking into that. I thought we already had a QA/QC tool in R. I also thought that Carlos was hesitant to make it too strict in terms of the units. That being said, it definitely makes sense that the variables have to match the timeSeries headings.

During our week together in March, I started working on an entry procedure document above. I am happy to keep working on it and welcome feedback. I will add the part about the variable names matching. I volunteer to continue working on that document, which I would love to be included as a supplement to the paper.

Best,
Caitlin

===================================
Caitlin Hicks Pries
Assistant Professor of Biological Sciences
Dartmouth College
Life Sciences Center, room 349
78 College St.
Hanover, NH  03755

603-646-2052
http://sites.dartmouth.edu/hicksprieslab/
@Carbon_Cait on Twitter

**Comment by jb388** [comment]
Great! I thought that we had started a "user guide" document, but I couldn't remember what happened to it. I think that would be a nice supplement to the paper, or at the least, super helpful for the website.

There's a QA/QC tool that checks which fields are missing from a given metadata file by comparing it to the template, but that's it as far as I can tell. 

As far as units, I thought that we had actually agreed on a list---not enforcing particular ones, per se, but enforcing how they are reported at least.

**Comment by christinaschaedel** [comment]
I think that sounds great. As a supplementary piece definitely useful

**Comment by ShaneStoner** [comment]
I know we agreed on a list of units, but I'm honestly not sure if it was 
ever written down on paper or electronically. Might be good to circulate 
a list and confirm them again?

Good work to Jeff and Caitlin!

**Comment by crlsierra** [comment]
Yes, a QA/QC function that checks correspondence between variables in the metadata file and the csv files is extremely important. Ideally, we would write separate functions that check different aspects of the functionality of the database. These function can be stored either in the `test` folder that already exist, or as a separate folder within the R package. 
The idea behind having multiple functions with different tests is that we can run all the tests automatically and easily detect what went wrong. The Travis CI framework that Jeff mentioned recently in an email can run all tests automatically. The important thing is that we write the tests in the first place.

As for the units, they are currently in the `template_metadata_workingfile.yaml` file.

**Comment by CaitlinPries** [comment]
Here is the list of unit recommendations:

Parameter
Unit
latitude and longitude
Decimal degrees
MAT
Celsius
MAP
mm
depth
cm, m
temperature
Celsius
moisture
percentGWC, percentFieldCapacity, percentWaterFilledPoreSpace
carbon
percent, mg/gSoil, g/gSoil, microg/gSoil
nitrogen
percent, mg/gSoil, g/gSoil, microg/gSoil
bulkDensity
g/cm3
redox
mV
fluxes
gC-CO2/gSoil, gC/gC, microgC/gC/h, molC/gSoil/d, or combinations of the above


===================================
Caitlin Hicks Pries
Assistant Professor of Biological Sciences
Dartmouth College
Life Sciences Center, room 349
78 College St.
Hanover, NH  03755

603-646-2052
http://sites.dartmouth.edu/hicksprieslab/
@Carbon_Cait on Twitter

**Comment by crlsierra** [comment]
I just finished implementing the test infrastructure for sidb. It consists of two parts, 1) specific tests about the data, and 2) tests for the entire R package. The specific tests are located in the folder `Rpkg/tests/testthat/`. It uses the `testthat` package to run very specific tests about the data. For example, at the moment there is one test that checks that all entries can be read in R. Another test checks that the names of the fields in the metadata files agree with the names in the metadata template. We can add more tests here as needed.
The general R tests are run by the commands `R CMD build` and `R CMD check`. A script in the test folder runs these commands automatically. I recommend everybody to run these tests before pushing anything to the repository. 
I'm also working on a continuous integration workflow in Travis CI, which will run all tests automatically in a remote server and notify us by email if something goes wrong. The tests are failing at the moment because of a problem with paths of directories in the remote machine. Once I figure it out, the test infrastructure will be ready and I will close this issue. 
Let me know if you have any comment or suggestion.

**Comment by jb388** [comment]
Nice going, Carlos! I also started writing some additional tests for the test framework. The additional test script "test_dataStructure" is now on the dev branch.

Currently there are two new tests: One looks to make sure the site names in the initiConditions.csv file match those in the siteInfo file; and one looks to make sure each table in the _variables_ list of the metadata file has the same number of fields.

**Comment by jb388** [comment]
@CaitlinPries 
I didn't see the allowable unit list for time variables in what you shared above. If I remember correctly, we had "d" for days, and "h" for hours. I think that was it?

**Comment by CaitlinPries** [comment]
Yes, it is day or hours according to the flux units, but yes we do need to add a time unit to that doc.

===================================
Caitlin Hicks Pries
Assistant Professor of Biological Sciences
Dartmouth College
Life Sciences Center, room 349
78 College St.
Hanover, NH  03755

603-646-2052
http://sites.dartmouth.edu/hicksprieslab/
@Carbon_Cait on Twitter

**Comment by jb388** [comment]
I'm closing this issue since QAQC is now accomplished via tests. More tests need to be written, but in the future we can create specific github issues for specific tests.
