### ISSUE TITLE
Readme.md links broken

### ISSUE THREAD

**Issue by CaitlinPries** [SoilBGC-Datashare/sidb#10]
All the links under the Data header in the paragraph below are broken. 

This folder contains all the data currently in SIDb. For each incubation study there is a yaml file with metada and a time series data file in .csv format. A list of the studies currently in SIDb (studies_list.csv), as well as a guide for entering new data (Readme.md), an annotated blank template file (template_metadata.yaml), and a blank initConditions.csv file are also located in this folder.

**Comment by jb388** [comment]
fixed
