### ISSUE TITLE
Instructions for data entry?

### ISSUE THREAD

**Issue by CaitlinPries** [SoilBGC-Datashare/sidb#11]
[InstructionsForDataEntry.docx](https://github.com/SoilBGC-Datashare/sidb/files/6306723/InstructionsForDataEntry.docx)

I wrote this for instructions on how to enter data a while back. I thought it was going to be included on the website or this repository, but I cannot find it. It would be useful to include here. Can someone link it to the Readme?

**Comment by jb388** [comment]
Hi Caitlin, thanks for pointing this out. I *think* (but could be wrong) that these instructions were updated and added as a [Readme.md](https://github.com/SoilBGC-Datashare/sidb/blob/master/data/Readme.md). I can easily link that file in the Readme.md file on the main page of the repo. Can you take a look to see if you think the file I linked is adequate?

**Comment by jb388** [comment]
Hmm, I clearly looked at this issue before I had my coffee: the instruction file I mentioned is already linked in the Readme on the main page of the repo, in the first section under "Data":

"...as well as a guide for entering new data (Readme.md)..."

If you have ideas about how to make it more visible/easier to find, feel free to edit the main Readme file directly. Or we can brainstorm ideas here and I can implement them.

**Comment by mazizirad** [comment]
Hi Jeff and Caitlin, 
It is easy to find the instruction file as it has been clearly linked on the main page of repository. But if you want to make it more visible I would suggest to add a bulleted list of important linked file in the main page.

**Comment by CaitlinPries** [comment]
Hi all,

It is possible I am l looking at an old version in git? Like maybe something is not updating for me? I am in the Master branch. None of the links under Data work for me including the Readme.md, which I think is the instruction file. When I click on the Readme.md in the files it just brings me to here (where none of the links work):

***@***.***D7312F.3FA4AE20]

===================================
Caitlin Hicks Pries
Assistant Professor of Biological Sciences
Dartmouth College
Life Sciences Center, room 349
78 College St.
Hanover, NH  03755

603-646-2052
http://sites.dartmouth.edu/hicksprieslab/
@Carbon_Cait on Twitter


From: Mina AziziRad ***@***.***>
Reply-To: SoilBGC-Datashare/sidb ***@***.***>
Date: Wednesday, April 14, 2021 at 10:08 AM
To: SoilBGC-Datashare/sidb ***@***.***>
Cc: Caitlin Hicks Pries ***@***.***>, Author ***@***.***>
Subject: Re: [SoilBGC-Datashare/sidb] Instructions for data entry? (#11)


Hi Jeff and Caitlin,
It is easy to find the instruction file as it has been clearly linked on the main page of repository. But if you want to make it more visible I would suggest to add a bulleted list of important linked file in the main page.

**Comment by jb388** [comment]
Hmm, strange. Is it possible that you are looking at an old forked copy of the repo that hasn't been updated?

@mazizirad do the readme links work for you?

FWIW The links *were* broken, but I changed the paths and now they are working on my machine.

**Comment by CaitlinPries** [comment]
I signed out and then signed back in and it works now! Thank you!

===================================
Caitlin Hicks Pries
Assistant Professor of Biological Sciences
Dartmouth College
Life Sciences Center, room 349
78 College St.
Hanover, NH  03755

603-646-2052
http://sites.dartmouth.edu/hicksprieslab/
@Carbon_Cait on Twitter


From: Jeff B ***@***.***>
Reply-To: SoilBGC-Datashare/sidb ***@***.***>
Date: Wednesday, April 14, 2021 at 1:42 PM
To: SoilBGC-Datashare/sidb ***@***.***>
Cc: Caitlin Hicks Pries ***@***.***>, Author ***@***.***>
Subject: Re: [SoilBGC-Datashare/sidb] Instructions for data entry? (#11)


Hmm, strange. Is it possible that you are looking at an old forked copy of the repo that hasn't been updated?

@mazizirad<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmazizirad&data=04%7C01%7CCaitlin.Hicks.Pries%40dartmouth.edu%7Cc1cc95a747c14e89040b08d8ff6cacbd%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637540189509535577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zTSAdk4%2BQnUd1tjHPpY0wUtub8HTHhiHWRPtBA2PXeE%3D&reserved=0> do the readme links work for you?

FWIW The links were broken, but I changed the paths and now they are working on my machine.

**Comment by mazizirad** [comment]
@jb388 Yes it works. I tried it couple of weeks ago once and was working without problem.
