### ISSUE TITLE
R version dependence in build

### ISSUE THREAD

**Issue by jb388** [SoilBGC-Datashare/sidb#5]
@crlsierra 
I ran the devtools::check_built function to make sure the changes I made hadn't affected package functionality and this was the only warning:
 
❯ checking DESCRIPTION meta-information ... WARNING
  Dependence on R version ‘3.4.3’ not with patchlevel 0

Perhaps you've seen this, but I'm not sure if this is a real issue, and if so, how best to approach it.

**Comment by crlsierra** [comment]
I haven't seen that warning either. It may be a machine specific warning, probably related to the R version you're using.
